# Use the official Node.js 20 image as the base image
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire codebase into the container
COPY . .

# Build the Next.js application
RUN npm run build


# Production stage to serve the Next.js application
FROM node:20-alpine AS runner

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/next.config.mjs ./
# Install only production dependencies
RUN npm install --omit=dev

# Expose port 3000
EXPOSE 3000

# Set environment to production
ENV NODE_ENV=production

# Run the Next.js application
CMD ["npm", "run", "start"]
