version: '3.8' # Updated version
services:
  node-app:
    container_name: iRecuit-app-container
    build: .
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules # Make sure node_modules are also mounted

    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - MONGO_HOST=iRectuit_db
      - MONGO_PASSWORD=example
      - MONGO_USER=root
      - MONGO_PORT=27017
    command: npm run start:dev # Ensure using the correct dev command for hot reload

  iRectuit_db:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_db:
