// src/formConfigs/jobSeekerFormConfig.ts

export const infoProfessionnellesFormConfig = {
  category: "info-professionnelles",
  title: {
    en: "Application",
    fr: "Candidature",
    ar: "طلب التوظيف",
  },
  description: {
    en: "This is how others will see you on the site.",
    fr: "C'est ainsi que les autres vous verront sur le site.",
    ar: "هكذا سيراك الآخرون على الموقع.",
  },
  fields: [
    {
      type: "group",
      title: "Parcours et diplômes",
      name: "parcoursEtDiplomes",
      description:
        "Merci d'ajouter tous vos diplômes après le bac. C'est obligatoire",

      group: [
        {
          type: "select",
          name: "parcoursEtDiplomes.origine",
          label: "Origine *",
          placeholder: "",
          options: [
            { value: "etranger", label: "Etranger" },
            { value: "marocainPrive", label: "Marocain privé" },
            { value: "marocainPublic", label: "Marocain public" },
          ],
        },

        {
          type: "text",
          name: "parcoursEtDiplomes.intituleDiplome",
          placeholder: "",
          label: "Intitulé de votre diplôme avec précision *",
        },

        {
          type: "select",
          name: "parcoursEtDiplomes.diplomeType",
          label: "Diplôme ou diplôme équivalent * ",
          placeholder: "",
          options: [
            {
              id: 1,
              value: "D0002",
              label: "Doctorat",
              labelAr: "الدكتوراه",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 2,
              value: "D0003",
              label: "Master",
              labelAr: "الماستر",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 3,
              value: "D0004",
              label: "Master spécialisé",
              labelAr: "الماستر المتخصص",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 4,
              value: "D0005",
              label: "Master en Sciences et Techniques",
              labelAr: "الماستر في العلوم والتقنيات",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 5,
              value: "D0006",
              label: "Licence des études fondamentales",
              labelAr: "الإجازة في الدراسات الأساسية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 7,
              value: "D0008",
              label: "Diplôme de docteur en médecine",
              labelAr: "دبلوم دكتور في الطب",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 8,
              value: "D0009",
              label: "Diplôme de docteur en médecine dentaire",
              labelAr: "دبلوم دكتور في طب الأسنان",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 11,
              value: "D0011",
              label: "Diplôme traducteur",
              labelAr: "دبلوم مترجم تحريري",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 12,
              value: "D0012",
              label: "Diplôme de docteur en pharmacie",
              labelAr: "دبلوم دكتور في الصيدلة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 13,
              value: "D0013",
              label: "Licence en sciences et techniques",
              labelAr: "الإجازة في العلوم والتقنيات",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 14,
              value: "D0014",
              label: "Licence professionnelle",
              labelAr: "الإجازة المهنية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 15,
              value: "D0015",
              label: "Diplôme universitaire de technologie",
              labelAr: "الدبلوم الجامعي للتكنولوجيا",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 16,
              value: "D0016",
              label: "Diplôme des écoles nationales de commerce et gestion",
              labelAr: "دبلوم المدارس الوطنية للتجارة والتسيير ",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 17,
              value: "D0017",
              label: "Diplôme d'ingénieur d'état",
              labelAr: "دبلوم مهندس الدولة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 22,
              value: "D0022",
              label: "Diplôme National de Spécialité d'Orthodentie",
              labelAr: "دبلوم التخصص في طب الأسنان",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 23,
              value: "D0023",
              label: "Diplôme de Spécialité Médicale",
              labelAr: "دبلوم التخصص في الطب",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 25,
              value: "D0025",
              label: "Licence en éducation ",
              labelAr: "الإجازة في التربية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 27,
              value: "D0027",
              label: "Diplôme d'interprète",
              labelAr: "دبلوم عالي في الترجمة الفورية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 28,
              value: "D0028",
              label: "Diplôme en traduction audio visuelle",
              labelAr: "دبلوم في الترجمة السمعية البصرية؛",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 40,
              value: "D0037",
              label: "Diplôme de Métiers d'Art et de Design",
              labelAr: "دبلوم في مهن الفنون والتصميم",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 41,
              value: "D0038",
              label:
                "Diplôme de l'Ecole Nationale Supérieure de l'Art et de Design",
              labelAr: "دبلوم المدرسة الوطنية العليا للفن والتصميم",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 51,
              value: "D0030",
              label:
                "Diplôme du Cycle Supérieur de l'Institut Supérieur International de Tourisme de Tanger",
              labelAr: "دبلوم السلك العالي للمعهد العالي الدولي للسياحة بطنجة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 52,
              value: "D0031",
              label:
                "Diplôme du Cycle Normal de l’Institut Supérieur International de Tourisme",
              labelAr: "دبلوم السلك العادي للمعهد العالي الدولي للسياحة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 53,
              value: "D0064",
              label:
                "Diplôme du Cycle Normal de l'Institut Supérieur des Etudes Maritimes ",
              labelAr: "دبلوم السلك العادي للمعهد العالي للدراسات البحرية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 54,
              value: "D0065",
              label:
                "Diplôme du Cycle supérieur de l'Institut Supérieur des Etudes Maritimes ",
              labelAr: "دبلوم السلك العالي للمعهد العالي للدراسات البحرية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 55,
              value: "D0042",
              label: "Diplôme de technicien spécialisé",
              labelAr: "شهادة تقني متخصص",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 56,
              value: "D0010",
              label:
                "DEUST- Diplôme des études générales dans les sciences et techniques",
              labelAr: "دبلوم الدراسات العامة في العلوم والتقنيات",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 57,
              value: "D0024",
              label: "DEUP- Diplôme des études universitaires professionnelles",
              labelAr: "دبلوم الدرسات الجامعيةالمهنية DEUP",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 58,
              value: "D0007",
              label: "DEUG- Diplôme des études universitaires générales",
              labelAr: "دبلوم الدرسات الجامعية العامة DEUG",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 59,
              value: "D0039",
              label: "Brevet de technicien spécialisé ",
              labelAr: "شهادة تقني متخصص",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 61,
              value: "D0066",
              label: "Licence ISCAE",
              labelAr: "Licence ISCAE",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 63,
              value: "D0044",
              label:
                "Diplôme d'Architecte des écoles nationales d'architecture",
              labelAr: "دبلوم مهندس معماري",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 64,
              value: "D0029",
              label:
                "Diplôme de l'institut Nationale d'Aménagement et d'Urbanisme",
              labelAr: "دبلوم المعهد الوطني للتهيئة والتعمير",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 65,
              value: "D0043",
              label: "Diplôme de Spécialité en pharmacie",
              labelAr: "دبلوم التخصص في الصيدلة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 66,
              value: "D0032",
              label: "Diplôme de Capitaine au Long Cours",
              labelAr: "دبلوم ربان أعالي البحار",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 67,
              value: "D0033",
              label: "Cycle fondamental INSAP",
              labelAr:
                "دبلوم السلك الأساسي المسلم من طرف المعهد الوطني لعلوم الآثار والتراث",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 68,
              value: "D0034",
              label:
                "ISCAE-Diplôme du Groupe Institut Supérieur de Commerce et d'Administration des Entreprises",
              labelAr: "دبلوم  مجموعة  المعهد العالي للتجارة وإدارة المقاولات",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 69,
              value: "D0035",
              label: "Diplôme d'informatiste",
              labelAr: "Diplôme d'informatiste",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 70,
              value: "D0036",
              label: "Diplôme d'informatiste spécialisé",
              labelAr: "Diplôme d'informatiste spécialisé",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 71,
              value: "D0041",
              label: "Attestation d'admissibilité au CNC",
              labelAr: "شهادة لاجتياز المباراة الوطنية  الموحدة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 72,
              value: "D0001",
              label: "Baccalauréat",
              labelAr: "البكالوريا",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 73,
              value: "D0045",
              label: "Diplôme d'Administrateur des Affaires Maritimes",
              labelAr: "دبلوم متصرف في الشؤون البحرية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 74,
              value: "D0046",
              label:
                "Diplôme de Capitaine Mécanicien de 1ère classe de la Marine Marchande",
              labelAr:
                "دبلوم ضابط ميكانيكي من الدرجة الأولى في الملاحة التجارية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 75,
              value: "D0047",
              label: "Diplôme de Cycle Normal en Information et Communication",
              labelAr: "دبلوم السلك العادي في الإعلام والتواصل",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 76,
              value: "D0048",
              label: "Diplôme de Cycle Supérieur",
              labelAr: "دبلوم السلك العالي",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 77,
              value: "D0049",
              label: "Diplôme de Lieutenant au Long Cours",
              labelAr: "دبلوم ملازم أعالي البحار",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 78,
              value: "D0050",
              label:
                "Diplôme de Lieutenant Mécanicien de 1ère classe de la Marine Marchande",
              labelAr:
                "دبلوم ملازم ميكانيكي من الدرجة الأولى في الملاحة التجارية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 79,
              value: "D0051",
              label: "Diplôme de l'Institut National des Beaux Arts",
              labelAr: "دبلوم المعهد الوطني للفنون الجميلة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 80,
              value: "D0052",
              label: "Diplôme du Cycle Normal",
              labelAr: "دبلوم السلك العادي",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 81,
              value: "D0053",
              label: "Diplôme National d'Expert Comptable",
              labelAr: "دبلوم وطني لخبير محاسب",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 82,
              value: "D0054",
              label: "Diplôme Officier Ingénieur d'Etat",
              labelAr: "دبلوم ضابط مهندس الدولة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 83,
              value: "D0055",
              label: "Diplôme Supérieur de Traduction",
              labelAr: "دبلوم عالي في الترجمة التحريرية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 84,
              value: "D0056",
              label: "Docteur Vétérinaire",
              labelAr: "دكتور بيطري",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 85,
              value: "D0057",
              label: "Docteur Vétérinaire Spécialisé",
              labelAr: "دكتور بيطري مختص",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 86,
              value: "D0059",
              label:
                "Certificat du deuxième cycle des écoles normales supérieures",
              labelAr: "شهادة السلك الثانيي للمدارس العليا للأساتدة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 87,
              value: "D0060",
              label:
                "Certificat du cycle supérieur délivré par les écoles normales supérieures",
              labelAr: "شهادة السلك العالي المسلمة من المدارس العليا للأساتدة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 88,
              value: "D0061",
              label: "Classes Préparatoires aux Grandes Ecoles",
              labelAr: "الأقسام التحضيرية للمدارس العليا",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 89,
              value: "D0019",
              label: "Diplôme d'études supérieures approfondies",
              labelAr: "دبلوم الدراسات العليا المعمقة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 90,
              value: "D0021",
              label: "Diplôme d'études supérieures spécialisées",
              labelAr: "دبلوم الدراسات العليا المتخصصة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 91,
              value: "D0020",
              label: "Doctorat d'Etat",
              labelAr: "دكتوراه الدولة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 96,
              value: "D0058",
              label: "Certificat d’aptitude à l’enseignement secondaire",
              labelAr: "شهادة الأهلية للتعليم الثانوي",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 97,
              value: "D0071",
              label: "Licence",
              labelAr: "الإجازة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 98,
              value: "D0075",
              label: "Licence en profession infirmière et techniques de santé",
              labelAr: "الإجازة في المهن التمريضية وتقنيات الصحة",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 99,
              value: "D0070",
              label: "Année préparatoire aux études vétériniares",
              labelAr: "السنة التحضيرية للدراسات البيطرية",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 100,
              value: "A0001",
              label: "Autres diplômes",
              labelAr: "دبلومات أخرى",
              type: "PUBLIC",
              grades: null,
            },
            {
              id: 101,
              value: "A0002",
              label: "Maîtrise",
              labelAr: "المتريز ",
              type: "PUBLIC",
              grades: null,
            },
          ],
        },

        {
          type: "text",
          name: "parcoursEtDiplomes.anneeObtention",
          label: "Année d'obtention du diplôme *",
          placeholder: "",
          dependsOn: null,
        },
        {
          type: "text",
          name: "parcoursEtDiplomes.specialite",
          label: "Spécialité *",
          placeholder: "",
          dependsOn: null,
        },
        {
          type: "text",
          name: "parcoursEtDiplomes.mention",
          label: "Mention *",
          placeholder: "",
          dependsOn: null,
        },
        {
          type: "text",
          name: "parcoursEtDiplomes.etablissement",
          label: "Etablissement *",
          placeholder: "Enter a link to your portfolio",
        },
        {
          type: "file",
          name: "parcoursEtDiplomes.diplomePdf",
          label: "Diplôme scané (Pdf, Max 10Mo) *",
        },
      ],
    },
    {
      type: "group",
      title: "Niveaux Langues",
      name: "niveauxLangues",
      description:
        "Langues : rubrique requise pour les postes d'enseignants, facultative pour les cadres administratifs et techniques",
      group: [
        {
          type: "select",
          name: "niveauxLangues.langue",
          label: "Langue *",
          placeholder: "",
          options: [
            {
              id: 1,
              label: "Arabe",
              value: "arabe",
              labelAr: "العربية",
            },
            {
              id: 2,
              label: "Amazigh",
              value: "amazigh",
              labelAr: "أمازيغية",
            },
            {
              id: 3,
              label: "Anglais",
              value: "anglais",
              labelAr: "الإنجليزية",
            },
            {
              id: 4,
              label: "Français",
              value: "français",
              labelAr: "الفرنسية",
            },
            {
              id: 5,
              label: "Espagnol",
              value: "espagnol",
              labelAr: "الإسبانية",
            },
            {
              id: 6,
              label: "Russe",
              value: "russe",

              labelAr: "الروسية",
            },
            {
              id: 7,
              label: "Allemand",
              value: "allemand",
              labelAr: "ألمانية",
            },
            {
              id: 8,
              label: "Italien",
              value: "italien",
              labelAr: "إيطالي",
            },
            {
              id: 9,
              label: "Portugais",
              value: "portugais",
              labelAr: "البرتغالية",
            },
            {
              id: 10,
              label: "Japonais",
              value: "japonais",
              labelAr: "اليابانية",
            },
            {
              id: 11,
              label: "Chinois",
              value: "chinois",
              labelAr: "صينى",
            },
            {
              id: 12,
              label: "Autres",
              value: "autres",
              labelAr: "لغات أخرى",
            },
          ],
        },
        {
          type: "select",
          name: "niveauxLangues.niveau",
          label: "Nuveau *",
          placeholder: "",
          dependsOn: "niveauxLangues.langue",

          options: [
            {
              label: " Avancé",
              value: "avance",
            },
            {
              label: " Basique",
              value: "basique",
            },
            {
              label: "Intermediare",
              value: "intermediare",
            },
          ],
        },
        {
          type: "file",
          label: "Cértificat (Pdf, Max 10Mo, Optionnel)",
          name: "niveauxLangues.certificatLanguePdf",
          placeholder: "",
          dependsOn: "niveauxLangues.langue",
        },
      ],
    },
    {
      type: "group",
      title: "Expérience pédagogique",
      name: "experiencePedagogique",
      description: "",
      group: [
        {
          type: "number",
          label: "Expérience pédagogique en heures *",
          name: "experiencePedagogique.experiencePedagogiqueEnHeures",
          placeholder: "",
        },
      ],
    },
    {
      type: "group",
      title: "Publications",
      name: "publications",
      description: "",
      group: [
        {
          type: "text",
          label: "Titre",
          name: "publications.titre",
          placeholder: "titre",
        },
        {
          type: "number",
          label: "Année de publication de l'article *",
          name: "publications.anneePublication",
          placeholder: "Année de publication de l'article",
          dependsOn: "publications.titre",
        },
        {
          type: "select",
          label: "Type *",
          name: "publications.type",
          placeholder: "",
          dependsOn: "publications.titre",

          options: [
            {
              id: 1,
              label:
                "Articles dans des revues indexées (Scopus et/ou WoS), selon Q1, Q2, Q3 et Q4 et selon premier auteur ou non",
              value:
                "Articles dans des revues indexées (Scopus et/ou WoS), selon Q1, Q2, Q3 et Q4 et selon premier auteur ou non",

              labelAr:
                "Articles dans des revues indexées (Scopus et/ou WoS), selon Q1, Q2, Q3 et Q4 et selon premier auteur ou non",
            },
            {
              id: 2,
              value:
                "Publications dans les proceedings indexés (Scopus et/ou Wos), selon premier auteur au non",
              label:
                "Publications dans les proceedings indexés (Scopus et/ou Wos), selon premier auteur au non",
              labelAr:
                "Publications dans les proceedings indexés (Scopus et/ou Wos), selon premier auteur au non",
            },
            {
              id: 3,
              value:
                "Articles dans des revues indexées dans le Portail des Revues Scientifiques Marocaines (PRSM), selon premier auteur ou non",
              label:
                "Articles dans des revues indexées dans le Portail des Revues Scientifiques Marocaines (PRSM), selon premier auteur ou non",
              labelAr:
                "Articles dans des revues indexées dans le Portail des Revues Scientifiques Marocaines (PRSM), selon premier auteur ou non",
            },
            {
              id: 4,
              label: "Brevets enregistrés (marocain, PCT)",
              value: "Brevets enregistrés (marocain, PCT)",

              labelAr: "Brevets enregistrés (marocain, PCT)",
            },
            {
              id: 5,
              label: "Ouvrages avec ISBN et indexés",
              value: "Ouvrages avec ISBN et indexés",

              labelAr: "Ouvrages avec ISBN et indexés",
            },
            {
              id: 6,
              label: "Chapitre d'ouvrage avec ISBN et indexé",
              value: "Chapitre d'ouvrage avec ISBN et indexé",

              labelAr: "Chapitre d'ouvrage avec ISBN et indexé",
            },
            {
              id: 7,
              label: "Autre",
              value: "Autre",
              labelAr: "Autre",
            },
          ],
        },
        {
          type: "text",
          label: "URL",
          name: "publications.url",
          placeholder: "URL",
          dependsOn: "publications.titre",
        },
        {
          type: "file",
          label: "Publication (Pdf, Max 10Mo) *",
          name: "publications.publicationPdf",
          placeholder: "",
          dependsOn: "publications.titre",
        },
      ],
    },
    {
      type: "group",
      title: "Communications",
      name: "communications",
      description: "",
      group: [
        {
          type: "text",
          label: "Titre",
          name: "communications.titre",
          placeholder: "titre",
        },
        {
          type: "number",
          label: "Année de publication de la communication *",
          name: "communications.anneeCommunication",
          placeholder: "Année de la communication",
          dependsOn: "communications.titre",
        },
        {
          type: "text",
          label: "URL",
          name: "communications.url",
          placeholder: "URL",
          dependsOn: "communications.titre",
        },
        {
          type: "file",
          label: "Communication (Pdf, Max 10Mo) *",
          name: "communications.communicationPdf",
          placeholder: "",
          dependsOn: "communications.titre",
        },
      ],
    },
    {
      type: "group",
      title: "Résidanat",
      name: "residanat",
      description: "",
      group: [
        {
          type: "file",
          label: "Résidanat",
          name: "residanat.residanatPdf",
          placeholder: "",
        },
      ],
    },
    {
      type: "group",
      title: "Autres documents",
      name: "autresDocuments",
      description: "",
      group: [
        {
          type: "text",
          label: "Intitulé",
          name: "autresDocuments.intitule",
          placeholder: "",
        },
        {
          type: "file",
          label: "Document (Pdf, Max 10Mo) *",
          name: "autresDocuments.documentPdf",
          placeholder: "",
          dependsOn: "autresDocuments.intitule",
        },
      ],
    },
  ],
};
