import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Type Imports
import type { ChildrenType } from "@/types/types";
import type { Locale } from "@/configs/i18n";

// HOC Imports
import TranslationWrapper from "@/hocs/TranslationWrapper";

// Config Imports
import { i18n } from "@/configs/i18n";
import { headers } from "next/headers";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
  params,
}: ChildrenType & { params: { lang: Locale } }) => {
  // Vars
  const headersList = headers();
  const direction = i18n.langDirection[params.lang];

  return (
    <TranslationWrapper headersList={headersList} lang={params.lang}>
      <html id="__next" lang={params.lang} dir={direction}>
        <body className="">
          <ToastContainer />
          {children}
        </body>
      </html>
    </TranslationWrapper>
  );
};

export default RootLayout;
